backport: kernel/extable.c: use address-of operator on section symbols
GCC 12.3.0 complains about following:

 kernel/extable.c: In function 'sort_main_extable':
 kernel/extable.c:37:59: error: comparison between two arrays [-Werror=array-compare]
    37 |         if (main_extable_sort_needed && __stop___ex_table > __start___ex_table) {
       |                                                           ^
 kernel/extable.c:37:59: note: use '&__stop___ex_table[0] > &__start___ex_table[0]' to compare the addresses

So lets fix it by backporting upstream commit 63174f61dfae
("kernel/extable.c: use address-of operator on section symbols").

References: PCF-1011
Signed-off-by: Petr Štetiar <petr.stetiar@prplfoundation.org>