Fix compile errors with CONFIG_WERROR=y
Build ATH 12.4.0 CS kernel 6.1.31 with CONFIG_WERROR=y,
GCC 12.3.0 (default in OpenWrt 23.05) and get errors:

drivers/mtd/nand/raw/qcom_nandc.c:326:78: error: excess elements in struct initializer [-Werror]
drivers/net/mdio/mdio-ipq4019.c:756:72: error: passing argument 2 of 'of_get_next_available_child' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
drivers/firmware/qcom_scm.c:2916:9: error: ISO C90 forbids mixed declarations and code [-Werror=declaration-after-statement]
net/ipv4/ipmr.c:3174:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]
net/ipv6/ip6mr.c:531:44: error: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type 'long unsigned int' [-Werror=format=]

Those errors are originally warnings. Because of CONFIG_WERROR=y,
they are treated as errors. Fixed them by applying
0630-Fix-compile-errors-with-CONFIG_WERROR.patch.

https://prplfoundationcloud.atlassian.net/browse/PCF-1228

Signed-off-by: Mike Chung <mike.chung@wnc.com.tw>